name: Deploy Static Website

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger deployments from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages (or other hosting provider)
      run: |
        # If you're deploying to GitHub Pages
        # Simply copy the files to the `gh-pages` branch or use a deploy tool
        echo "Deploying static website"
      
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
